const vendor = [
  'babel-polyfill',
  'react',
  'react-dom',
  'react-redux',
  'react-router',
  'react-router-redux',
  'react-virtualized',
  'redux',
  'redux-observable',
  'react-hot-loader',
  'rxjs',
  'lodash',
  'moment',
  'localforage',
  'react-loadable',
  'redux-persist',
  'redux-persist-transform-filter',
  'redux-api-middleware',
  'jwt-decode',
  'react-transition-group',
];
module.exports = vendor;